#!/bin/bash

echo "Start of ${0} - Used to test terraform locally"

## Example
## ./local_terraform init
## ./local_terraform apply -auto-approve


WS_NAME="ws_name_from_local"
WS_MAJOR_VERSION="0"
WS_VERSION_UNDERSCORE="0_1_23"
TF_STATE_BASE="./state"
KONG_ADMIN_URI="http://kong:8001"

if [[ ! -d ${TF_STATE_BASE}/${WS_NAME}/${WS_MAJOR_VERSION} ]]; then
  mkdir -p ${TF_STATE_BASE}/${WS_NAME}/${WS_MAJOR_VERSION}
fi

EXTRAPARAM=-state="${TF_STATE_BASE}/${WS_NAME}/${WS_MAJOR_VERSION}/terraform.tfstate"
if [[ E${1} == "Einit" ]]; then
  EXTRAPARAM="-backend-config path=${TF_STATE_BASE}/${WS_NAME}/${WS_MAJOR_VERSION}"
fi

docker run --rm -it -v $(pwd):/curdir/ \
  --workdir=/curdir \
  --network=main_net \
  -e TF_VAR_ws_name="${WS_NAME}" \
  -e TF_VAR_major_version="${WS_MAJOR_VERSION}" \
  -e TF_VAR_version_underscore="${WS_VERSION_UNDERSCORE}" \
  -e TF_VAR_kong_admin_uri="${KONG_ADMIN_URI}" \
  hashicorp/terraform:0.14.4 $@ ${EXTRAPARAM}

echo "End of ${0}"
